import type { Metadata } from "next";
import "./globals.css";

import { Inter } from 'next/font/google';

import Image from "next/image";
import blob from "./blob.svg";
import blob2 from "./blob-2.svg";

import Navbar from "./components/navbar";
import Footer from "./components/footer";

import LenisScroll from "./components/lenisScroll";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Adrian Morbán",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased overflow-x-hidden`}>
        <LenisScroll />
        <Navbar />
        <main className="z-10 relative bg-black">
          <div className="overlay">
            <Image className="blur-[200px] w-[75%] opacity-30 -top-[55%] absolute -left-[35%]" src={blob} alt="Blob" />
            <Image className="blur-[200px] w-[75%] opacity-20 -bottom-[55%] absolute -right-[40%]" src={blob2} alt="Blob" />
          </div>
          <div className="-mt-[100vh]">
            {children}
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
