import type { Metadata } from "next";
import "./globals.css";

import { Inter } from 'next/font/google';

import Image from "next/image";
import blob from "./blob.svg";
import blob2 from "./blob-2.svg";

import Navbar from "./components/navbar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Adrian Morbán",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="overlay z-10">
          <Image className="blur-[200px] w-[75%] opacity-20 -top-[55%] absolute -left-[35%]" src={blob} alt="Blob" />
          <Image className="blur-[200px] w-[75%] opacity-15 -bottom-[55%] absolute -right-[40%]" src={blob2} alt="Blob" />
        </div>
        <main className="relative">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
