import type { Metadata } from "next";
import "./globals.css";
import "animate.css";
import { ModalProvider } from "./context/modalContext";
import { LanguageProvider } from "./context/languageContext";
import { LoaderProvider } from "./context/loaderContext";
import Loader from "./components/loader";

import { Inter } from 'next/font/google';

import Image from "next/image";
import blob from "./blob.svg";
import blob2 from "./blob-2.svg";

import Navbar from "./components/navbar";
import Footer from "./components/footer";
import Modal from "./components/modal";
import ProjectModal from "./components/projectModal";

import LenisScroll from "./components/lenisScroll";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Adrian Morbán",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased overflow-x-hidden`}>
        <LoaderProvider>
          <Loader />
          <LanguageProvider>
            <ModalProvider>
              <LenisScroll />
              <Navbar />
              <main className="bg-black relative z-10">
                <div className="overlay pointer-events-none">
                  <Image className="blur-[200px] w-[75%] opacity-30 -top-[55%] absolute -left-[35%]" src={blob} alt="Blob" />
                  <Image className="blur-[200px] w-[75%] opacity-20 -bottom-[55%] absolute -right-[40%]" src={blob2} alt="Blob" />
                </div>
                <div className="-mt-[100vh]">
                  {children}
                </div>
              </main>
              <Modal />
              <ProjectModal />
              <Footer />
            </ModalProvider>
          </LanguageProvider>
        </LoaderProvider>
      </body>
    </html>
  );
}
